### PR TITLE
Fixes for the module

### PR DESCRIPTION
**Pull request by sanguinariojoe**
A bunch of fixes coming from the PR done for the main source code tree (see https://github.com/FreeCAD/FreeCAD/pull/4870)

### CODE REVIEW

**Comment by luzpaz** [comment]
@looooo maybe transfer ownership to @sanguinariojoe repo like other external workbenches?

**Comment by looooo** [comment]
@luzpaz sry I am not able to do this (no rights). Maybe @yorikvanhavre can add @sanguinariojoe to the admin list of the repo.

**Comment by luzpaz** [comment]
Alternative, redirect `FreeCAD/freecad.ship` to `sanguinariojo/freecad.ship` and update the addon manager?

**Comment by sanguinariojoe** [comment]
> Alternative, redirect FreeCAD/freecad.ship to sanguinariojo/freecad.ship and update the addon manager?

+1

**Comment by yorikvanhavre** [comment]
Done! I added @sanguinariojoe to the FreeCAD developers team (you need to accept an invitation somewhere, @sanguinariojoe ) which gives you write access to all the addon repos @ FreeCAD, including ship and plot

**Pull request merged**
