### PR TITLE
Add package.xml

### LINKED ISSUE #38: Update to new AddonManager metadata schema
https://github.com/FreeCAD/FreeCAD-addons/issues/200

### PR DESCRIPTION
**Pull request by luzpaz**
Adding `package.xml` but it is not fully complete. Please review and also ascertain if anything else is necessary by referencing https://wiki.freecad.org/Package_Metadata

Closes #38

### CODE REVIEW

**Comment by luzpaz** [comment]
CC @chennes

**Comment by luzpaz** [comment]
ping @sanguinariojoe

**Comment by luzpaz** [comment]
@sanguinariojoe lets get this in before the v0.20 release

**Comment by sanguinariojoe** [comment]
Sorry! Busy days

**Pull request merged**
